# Generated by Django 5.1.7 on 2025-04-15 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0034_remove_inventory_detect_inventory_overburden_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="inventory",
            name="backpack_capacity",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="inventory",
            name="backpack_contents",
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name="inventory",
            name="is_backpack",
            field=models.BooleanField(default=False),
        ),
    ]
