# Generated by Django 5.1.7 on 2025-04-18 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0035_inventory_backpack_capacity_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="inventory",
            name="backpack_contents",
            field=models.JSONField(blank=True, default=list, null=True),
        ),
    ]
